Show NavFile Tag
tgrosinger/recent-files-obsidian pull request #105
Opened 2024-11-14 04:54 UTC by zayKenyon

Closes #92.

Perhaps the new path tooltip removes the need for this, however, this addition would bring the functionality of the Recent Files pane closer to that of the Explorer tab.

I've implemented CSS changes that make it look right, though happy to make adjustments if it needs technically fixing.

2024-11-22 18:05 UTC, tgrosinger requested changes
Thanks for the PR. I like the direction of making this interface look more like the file explorer. Just a couple changes needed.

2024-11-22 18:05 UTC, tgrosinger commented on main.ts
> +      // from: https://stackoverflow.com/a/4250408/617864
Instead of using regex for this, can we use the extension from the Obsidian api?

```
      const tFile = this.app.vault.getFileByPath(currentFile.path);
      const extension = tFile?.extension
      if (extension && extension !== 'md') {
        navFileTag.setText(extension)
      }
```

2024-11-22 18:05 UTC, tgrosinger commented on styles.css
> +  flex-grow: 1;
This is making it so that clicking any of the empty space after the name/extension will remove the item from the recent files list.

2024-11-23 04:50 UTC, zayKenyon commented on styles.css
> +  flex-grow: 1;
Ah, whoops! 

I'm not sure how to fix this 😅, I've been trying to create two boxes within the File Preview, one for the Title + NavTag, and the other for the X button, then align the first to the left and the second to the right, though I can't quite get it to work. 

Sorry for introducing changes I can't fix.

2024-11-27 20:24 UTC, tgrosinger commented on styles.css
> +  flex-grow: 1;
No worries. I added a new spacer div and set that to `flex-grow: 1`. Merged as ddbae59.

2024-11-27 20:24 UTC, closed without merging

2024-11-27 20:24 UTC, tgrosinger commented
Merged as ddbae59.